### ISSUE TITLE
Move agridat to Suggests

### ISSUE THREAD

**Issue by kwstat** [jangelini/geneticae#6]
Greetings.  Thanks for using my `agridat` package.  Would you mind changing the DESCRIPTION file so that `agridat` is in the `Suggests` field?  Then when you want to use data in a vignette or example, you do so with code like this:
```
library(agridat)
data(yan.winterwheat)
```

This change will make it easier for me to submit new versions of `agridat` to CRAN.

**Comment by jangelini** [comment]
Greetings, we have already made the change to make it easier for you to send new versions of `agridat`.

**Comment by kwstat** [comment]
Thanks.
